use std::{f32::consts::PI, time::Duration};

use tokio::{select, sync::mpsc};

use crate::prelude::*;

pub struct Manager {
    /// how much time between taking snapshots
    snapshot_ms: u64,
    /// how much time to wait on a device messaging the manager
    wait_for: u64,
}

/// See [`TestCamera`]'s notes about `Default`. This trait can be "derived", which means
/// code that is automatically generated by rust.
impl Default for Manager {
    fn default() -> Self {
        Self {
            // every 2 milliseconds, take a picture
            snapshot_ms: 2,
            wait_for: 200,
        }
    }
}

impl Manager {
    /// So we have these funky looking `C, M, F` here. What I'm doing is saying, I accept any type C that implements `Camera`.
    ///
    /// This is particularly useful when it comes to testing, because you can debug where this logic falters without
    /// having to worry about running physical devices
    pub async fn run<C, M, F>(self, camera: C, mirror: M, fan: F) -> Result<()>
    where
        C: Camera,
        M: Mirror,
        F: Fan,
    {
        // this is the fun part. We're going to make a thread for every type, and use channels to coordinate actions/movement.
        let (send_me_messages, mut receive_messages) = mpsc::channel(50);

        // Create async threads for our types that we will use to coordinate
        let (set_fanspeed, recv_fanspeed) = mpsc::channel(10);
        tokio::spawn(fan_handler(fan, send_me_messages.clone(), recv_fanspeed));

        let (take_picture, recv_take_picture_cmd) = mpsc::channel(10);
        tokio::spawn(camera_handler(camera, recv_take_picture_cmd));

        let (set_mirror_theta, recv_mirror_theta) = mpsc::channel(10);
        tokio::spawn(mirror_handler(
            mirror,
            send_me_messages.clone(),
            recv_mirror_theta,
        ));

        // first thing we'll do is set the fanspeed to match the rotation.
        // Assuming there are four blades on this fan
        let full_rotation_ms = self.snapshot_ms as f32 * 4.;
        let full_rotation_seconds = full_rotation_ms / 1000.;
        let ideal_fan_rotation = 1. / full_rotation_seconds;
        set_fanspeed.send(SetFanSpeed(ideal_fan_rotation)).await?;

        // It took time to send this message to get to this point.
        // You would ideally have other messages like, "begin emitting fan speed"
        // or the like to tell everyone that we're ready to go. Could
        // send a channel into all of these like "BroadcastMessage" or something.

        let mut current_fanspeed = 0.;
        let mut current_fan_position = 0.;
        let mut current_mirror_rotation = 0.;
        let mut num_pics_taken = 0;

        let print_stats = |msg: Option<&str>| match msg {
            Some(msg) => {
                println!(
                    "(fanspeed: {current_fanspeed:02}, fanpos: {current_fan_position:02}, mirror_t: {current_mirror_rotation:02}): {msg}"
                );
            }
            None => {
                println!(
                    "(fanspeed: {current_fanspeed:02}, fanpos: {current_fan_position:02}, mirror_t: {current_mirror_rotation:02})"
                );
            }
        };

        let mut times_looped = 0;

        let mut picture_state = PictureState::Ready;
        loop {
            // this can run into a potential issue where one sender
            // is dominating, meaning that only one of these branches frequently completes.
            // You can handle this by decreasing the channel size of senders, or tell
            // it to be quiet with another message.
            tokio::select! {
                new_message = receive_messages.recv() => {
                    let Some(new_message) = new_message else {
                        // if we reach this point, one of the threads has panicked.
                        // This is kinda unrecoverable. I just return an end to the manager here.
                        return Ok(());
                    };
                    match new_message {
                        ManagerMsg::Fanspeed(fan_state) => {
                            current_fanspeed = fan_state.current_rps;
                            current_fan_position = fan_state.position;

                        }
                        ManagerMsg::MirrorTheta(theta) => {
                            current_mirror_rotation = theta;
                        }
                    }
                }
                // if no message has been send within the past 200 milliseconds, error out. something is wrong.
                _ = tokio::time::sleep(Duration::from_millis(self.wait_for)) => {
                    return Err(anyhow!("Devices are not communicating, and we have waited LONG ENOUGH!"));
                }
            }

            // check if the fanspeed is up to par. like this is an example, so im not calculating delta nothing.
            // I think the interface would probably do a delta or something to make sure everything is properly aligned,
            // or the fanspeed can be self contained.
            //
            // Here, we just continue because it's clear the fan hasn't ramped up to the right speed yet.
            if (ideal_fan_rotation - current_fanspeed).abs() > 2. {
                println!(
                    "(fanspeed: {current_fanspeed:.2}, fanpos: {current_fan_position:.2}, mirror_t: {current_mirror_rotation:.2}, pics_taken: {num_pics_taken}): Fan not up to speed!"
                );
                continue;
            }
            // let's say a position 0, pi/2, pi, and 3pi/2 with a tolerance of pi/6 is a clearance to snap a picture. would have to know
            // width of fanblades
            let clearance_positions = [0., PI / 2., PI, 3. * PI / 2.];
            let tolerance = PI / 6.;

            // Normalize position to [0, 2pi)
            let mut pos = current_fan_position % (2. * PI);
            if pos < 0. {
                pos += 2. * PI
            }

            let mut msg = format!("Picture State: {picture_state:?}");
            let mut can_snap_pic = false;

            for gap in clearance_positions {
                let mut diff = pos - gap.abs();
                //wraparound
                diff = diff.min(2. * PI - diff);
                if diff <= tolerance {
                    can_snap_pic = true;
                    break;
                }
            }
            match picture_state {
                PictureState::Ready if can_snap_pic => {
                    take_picture.send(TakePicture).await?;
                    num_pics_taken += 1;
                    /// the state is now took picture
                    if times_looped % 10 == 0 {
                        msg.push_str(";Mirror updated");
                        set_mirror_theta
                            .send(SetMirrorTheta(times_looped as f32 * 0.12345678))
                            .await?;
                    }
                    picture_state = PictureState::PictureAlreadyTaken;
                }
                PictureState::Obstructed if can_snap_pic => {
                    // we'll snap on the next frame. could also merge with the above logic ^
                    picture_state = PictureState::Ready;
                }
                PictureState::PictureAlreadyTaken if !can_snap_pic => {
                    picture_state = PictureState::Obstructed;
                }
                _ => {}
            }

            println!(
                "(fanspeed: {current_fanspeed:.2}, fanpos: {current_fan_position:.2}, mirror_t: {current_mirror_rotation:.2}, pics_taken: {num_pics_taken}): {msg}"
            );
            times_looped += 1;
        }
    }
}

/// A state machine to determine if a picture should be taken by the camera
#[derive(Clone, Copy, Debug)]
enum PictureState {
    /// The camera is obstructed by a fan blade
    Obstructed,
    /// The camera has taken a picture during this fan blade gap
    PictureAlreadyTaken,
    /// The camera is ready to take a picture
    Ready,
}

pub enum ManagerMsg {
    Fanspeed(FanState),
    MirrorTheta(f32),
}

pub struct SetFanSpeed(f32);
pub struct SetMirrorTheta(f32);
pub struct TakePicture;

/// Most of the docs about these messages are here.
async fn fan_handler<F: Fan>(
    mut fan: F,
    msg_manager: mpsc::Sender<ManagerMsg>,
    mut recv_fanspeed_msg: mpsc::Receiver<SetFanSpeed>,
) -> Result<()> {
    loop {
        // So this is a macro that allows us to await one of two things.
        // The first one that finishes will be the branch that executes.
        //
        // In this case, we're going to wait for a response from the fan
        // to get its rotations per second.
        // If we were only dealing with rotations per second, code like
        // ```rust
        // let current_rps = fan.rotations_per_second().await?;
        // ```
        // would suffice. That's essentially what we're doing here
        //
        //
        // Note: I am not considering the instantaneous position of the fan blade.
        // This is just for example purposes. I'm going to pretend magic is involved :D
        tokio::select! {
            current_fan_state = fan.current_state() => {
                // `current_rps` is a `Result<f32, anyhow::Error>`.
                // Now, if we wanted to (as we do elsewhere), we could say
                // ```rust
                // let current_rps = current_rps?;
                // ```
                // However, I'll gracefully handle this error here for example purposes.
                // The `?` is syntactic sugar
                // that will make this function return if it is a failure. You can handle this error
                // gracefully using
                match current_fan_state {
                    /// The result is good!
                    Ok(current_fan_state) => {
                        // send a message to our channel that this is the current fanspeed.
                        msg_manager.send(ManagerMsg::Fanspeed(current_fan_state)).await?;
                    }
                    Err(e) => {
                        /// print out to stderr that we errored
                        eprintln!("Error: {e:?}");
                    }
                }
            }
            set_fanspeed_to = recv_fanspeed_msg.recv() => {
                // We can destructure an `Option`. Option looks like
                // ```rust
                // enum Option<T> {
                //   Some(T),
                //   None
                // }
                // ```
                let Some(SetFanSpeed(new_fanspeed)) = set_fanspeed_to else {
                    return Ok(());
                };
                fan.set_rotations_per_second(new_fanspeed).await?;
            }
        }
    }
    Ok(())
}

async fn camera_handler<C: Camera>(
    mut camera: C,
    mut recv_take_picture: mpsc::Receiver<TakePicture>,
) -> Result<()> {
    // you could provide some data in take picture like take this picture in, but
    // I'm assuming this is instantaneous
    while let Some(_take_picture_command) = recv_take_picture.recv().await {
        camera.take_picture().await?;
    }
    Ok(())
}

async fn mirror_handler<M: Mirror>(
    mut mirror: M,
    msg_manager: mpsc::Sender<ManagerMsg>,
    mut recv_mirror_rotation: mpsc::Receiver<SetMirrorTheta>,
) -> Result<()> {
    loop {
        tokio::select! {
            current_mirror_theta = mirror.theta() => {
                let theta = current_mirror_theta?;
                msg_manager.send(ManagerMsg::MirrorTheta(theta)).await?;

            }
            set_theta_to = recv_mirror_rotation.recv() => {
                let Some(set_theta) = set_theta_to else {
                    return Ok(())
                };
                mirror.set_theta(set_theta.0).await?;

            }
        }
    }
    Ok(())
}
