use crate::prelude::*;

pub struct Manager {
    /// how much time between taking snapshots
    snapshot_ms: u64,
}

impl Manager {
    pub async fn run<C, M, F>(self, camera: C, mirror: M, fan: F) -> Result<()>
    where
        C: Camera,
        M: Mirror,
        F: Fan,
    {
        todo!()
    }
}

/// See [`TestCamera`]'s notes about `Default`. This trait can be "derived", which means
/// code that is automatically generated by rust.
impl Default for Manager {
    fn default() -> Self {
        Self {
            // every 2 milliseconds, take a picture
            snapshot_ms: 2,
        }
    }
}
