use crate::prelude::*;

pub struct Manager {
    /// how much time between taking snapshots
    snapshot_ms: u64,
}

impl Manager {
    /// So we have these funky looking `C, M, F` here. What I'm doing is saying, I accept any type C that implements `Camera`.
    ///
    /// This is particularly useful when it comes to testing, because you can debug where this logic falters without
    /// having to worry about running physical devices
    pub async fn run<C, M, F>(self, camera: C, mirror: M, fan: F) -> Result<()>
    where
        C: Camera,
        M: Mirror,
        F: Fan,
    {
        todo!()
    }
}

/// See [`TestCamera`]'s notes about `Default`. This trait can be "derived", which means
/// code that is automatically generated by rust.
impl Default for Manager {
    fn default() -> Self {
        Self {
            // every 2 milliseconds, take a picture
            snapshot_ms: 2,
        }
    }
}
